### ISSUE TITLE
dualhooked lmafo 🤓

### ISSUE THREAD

**Issue by ScriptUnix** [vesperlol/Cookay#5]
outdated+dualhooked

this is skidded 💀

**Comment by vesperlol** [comment]
You must be fucking stupid.. this is not skidded or outdated tf, I would like you to send a image of where I "skidded" Cookay. Its a project I coded in vc with friends to show them a little bit about tkinter. Its also not outdated, browser_cookie3 still works perfectly , you even use that library in one of your project.. Also where's the dualhook ?

**Comment by ScriptUnix** [comment]
ur programs are shit
